plugins {
    id 'com.android.application'
}

android {
    namespace 'com.reboot.guard'
    compileSdk 35

    defaultConfig {
        applicationId "com.reboot.guard"
        minSdk 26
        targetSdk 33
        versionCode 6
        versionName "4.1.2-emergency-ui"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
